"""empty message

Revision ID: 21de7ab2d1ba
Revises: eb9b4d0ab06c
Create Date: 2020-01-02 12:22:56.520556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21de7ab2d1ba'
down_revision = 'eb9b4d0ab06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employee',
    sa.Column('employee_type', sa.Enum('LINE_MANAGER', 'PROJECT_MANAGER', 'EMPLOYEE', name='employeetypes'), nullable=True))
    op.add_column('Employee',
    sa.Column('super_admin', sa.Boolean(), nullable=True))
    op.add_column('Employee',
    sa.Column('phonenumber', sa.String(length=15), nullable=False))
    # sa.UniqueConstraint('phonenumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee','employee_type')
    op.drop_column('employee', 'super_admin')
    op.drop_column('employee', 'phonenumber')
    # op.drop_index('employee', 'phonenumber')
    # ### end Alembic commands ###
