"""empty message

Revision ID: 28fd7bf04d64
Revises: 21de7ab2d1ba
Create Date: 2020-01-08 16:03:09.124020

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28fd7bf04d64'
down_revision = '21de7ab2d1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('employee',
        sa.Column('joinDate', sa.Date(), nullable=False),
    )
    op.add_column('employee',
                  sa.Column('leaveDate', sa.Date(), nullable=False),
    )
    op.add_column('employee',
                  sa.Column('designation', sa.Unicode(length=80), nullable=False),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee", "joinDate")
    op.drop_column("employee", "leaveDate")
    op.drop_column("employee", "designation")
    # ### end Alembic commands ###
