"""empty message

Revision ID: 4073808d5814
Revises: 
Create Date: 2020-01-14 13:22:14.565961

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4073808d5814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KPI',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpiAttribute', sa.Unicode(length=80), nullable=False),
    sa.Column('initiateDate', sa.Date(), nullable=False),
    sa.Column('initiateMonth', sa.Unicode(length=80), nullable=False),
    sa.Column('initiateYear', sa.Unicode(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiateDate', sa.Date(), nullable=False),
    sa.Column('completionDate', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departName', sa.Unicode(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Unicode(length=80), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('kpi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['Comments.id'], ),
    sa.ForeignKeyConstraint(['kpi_id'], ['KPI.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.Unicode(length=80), nullable=False),
    sa.Column('lastName', sa.Unicode(length=80), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('designation', sa.Unicode(length=80), nullable=False),
    sa.Column('cnic', sa.String(length=13), nullable=False),
    sa.Column('phonenumber', sa.String(length=15), nullable=False),
    sa.Column('joinDate', sa.String(length=15), nullable=True),
    sa.Column('leaveDate', sa.String(length=15), nullable=True),
    sa.Column('employee_type', sa.Enum('LINE_MANAGER', 'PROJECT_MANAGER', 'EMPLOYEE', name='employeetypes'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnic'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phonenumber')
    )
    op.create_table('Form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('issueDate', sa.Date(), nullable=False),
    sa.Column('noOfFormGenerate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['Form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('teamName', sa.Unicode(length=80), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Team')
    op.drop_table('Form')
    op.drop_table('Employee')
    op.drop_table('Comments')
    op.drop_table('department')
    op.drop_table('Reviews')
    op.drop_table('KPI')
    # ### end Alembic commands ###
